apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoserver
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: geoserver
          image: image-registry.openshift-image-registry.svc:5000/pandeyrr-prod/geoserver:latest
